Made the account id variable

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,7 @@ workflows:
             [lint_terraform, build_gem_cache, package_lambda_artifact]
       - sirius-api-gateway/test_sirius_access:
           name: test_sirius_access
+          aws-account: '288342028542'         # Sirius dev AWS account
           requires: [apply_development]
       - sirius-api-gateway/newman_api_test:
           filters:
@@ -132,6 +133,10 @@ orbs:
           - run: bundle install --path vendor/bundle --quiet
           - run: bundle exec rake terraform:apply
       unit_test_lambdas:
+        #
+        # Runs the unit tests packaged with the lambda
+        #   We do this separately to `package_lambda_artifact` due to the extra requirements that are installed.
+        #
         executor: python-build
         steps:
           - checkout
@@ -177,23 +182,38 @@ orbs:
                 - api_test_config-{{ .Branch }}-{{ .Revision }}
           - run: newman run https://www.getpostman.com/collections/c85538a8e4fb4f19b892 -e /tmp/generated.postman_environment.json
       test_sirius_access:
+        #
+        # Tests if the provisioned lambda can communicate with the Sirius membrane.
+        #   - Does it get a positive response from the health check; and
+        #   - Does it get a positive response from an authentication attempt.
+        #
+        parameters:
+          aws-account:
+            description: AWS account teh lambda is deployed to
+            type: string
         executor: python
         steps:
           - run: sudo pip3 install awscli --upgrade
           - run:
+              # Assume the needed role and invoke the lambda
               name: Invoke simulate_sirius_access lambda
               command: |
-                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::288342028542:role/ci --role-session-name ci)
+                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::<< parameters.aws-account >>:role/ci --role-session-name ci)
                 export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                 export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                 export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                 aws lambda invoke --invocation-type RequestResponse --function-name simulate_sirius_access --region eu-west-1 --log-type Tail outputfile.txt > lambda-result.json
           - run:
+              # Output the result in full to aid in fault finding
               name: Dump output
               command: cat lambda-result.json
           - run:
+              # Decode the base64 element to aid in fault finding
               name: Decode lambda log
               command: cat lambda-result.json | jq -r '.LogResult' | base64 -d
           - run:
+              # Result an error from this step if an error was thrown by the lambda
               name: Test to ensure there was no error
+              # There's an error if the 'FunctionError' key is within the response
+              # If has() does not return false, an empty line is returned, thus `read line || exit 1` executes the latter.
               command: cat lambda-result.json | jq -r 'has("FunctionError")' | grep false | read line || exit 1
